/**
 * Insight metadata — the client-side concerns are:
 *  - Which assets are valid (`INSIGHT_ASSETS`)
 *  - The 100 KB cap on the serialized JSON
 *  - A filename convention so Recent Insights can filter and label
 *    Walrus uploads by the list endpoint alone.
 *
 * The blob shape (`InsightBody`) is data-driven: the user provides a
 * title + asset + which data cards to include in the wizard on
 * `/app/add-insight`. The markdown `analysis` field is AI-generated by
 * the MiniMax route (`/api/insights/generate`) and passed back in via
 * `buildInsightBody`. The raw data backing that markdown lives in
 * `includes` so consumers can re-render or analyze programmatically
 * without re-fetching.
 *
 * The list of uploads is fetched live from Tatum on every mount — there
 * is no client-side mirror of the registry. The asset lives in the
 * filename (`insight-{ASSET}-{timestamp}.json`) so the list endpoint
 * alone is enough to render the table; the full body is lazily fetched
 * via `fetchInsightBlob` only when a row is opened.
 */

export type InsightAsset = 'BTC' | 'SUI' | 'WAL';
export const INSIGHT_ASSETS: readonly InsightAsset[] = ['BTC', 'SUI', 'WAL'] as const;

export const INSIGHT_MAX_BYTES = 100 * 1024;
export const INSIGHT_FILENAME_PREFIX = 'insight-';

// ─── Body types ─────────────────────────────────────────────────────────────

/**
 * Raw SVI parameters at the moment the insight was published. Stored
 * unscaled — `a/b/m/sigma` are × 1e8 and `rho` is × 1e9 (matching the
 * on-chain SVI encoding used by the predict-server API).
 */
export interface SVIRaw {
  a: number;
  b: number;
  rho: number;
  m: number;
  sigma: number;
}

/**
 * A snapshot of the predict market at publish time. Captures SVI, spot /
 * forward, IVs at 5 standard strikes relative to spot, and the last
 * 30 spot price points. All money values are in USD (already divided by
 * PRICE_SCALE).
 */
export interface PredictSnapshot {
  oracleId: string;
  expiryMs: number;
  spot: number;
  forward: number;
  svi: SVIRaw;
  standardStrikes: Array<{ strike: number; up: number; down: number; iv: number }>;
  recentPrices: Array<{ time: number; spot: number }>;
}

/**
 * Compact representation of a Polymarket market embedded in the blob.
 * Only the fields the analysis needs to render + a couple of identifying
 * fields (id, sourceUrl) for navigation/verification.
 */
export interface PolymarketMarket {
  id: string;
  question: string;
  outcomes: Array<{ name: string; price: number }>;
  volume: number;
  liquidity: number;
  closeTime: string;
  sourceUrl: string;
}

/**
 * The JSON body uploaded to Walrus. Two parts:
 *  - `analysis` — auto-generated markdown, what a human reader sees.
 *  - `includes` — the raw data backing that markdown, so programmatic
 *    consumers don't have to re-fetch from upstream APIs.
 */
export interface InsightBody {
  title: string;
  asset: InsightAsset;
  timestamp: number;
  tag?: string;
  source?: string;
  analysis: string;
  includes: {
    predict?: PredictSnapshot;
    polymarket?: { markets: PolymarketMarket[] };
    kalshi?: { tickers: string[] };
  };
}

export interface InsightBodyInput {
  title: string;
  asset: InsightAsset;
  timestamp: number;
  tag?: string;
  source?: string;
  /** Pre-computed (AI-generated) markdown analysis. */
  analysis: string;
  includes: InsightBody['includes'];
}

// ─── Filename helpers ───────────────────────────────────────────────────────

export function insightFilename(asset: InsightAsset, timestamp: number): string {
  return `${INSIGHT_FILENAME_PREFIX}${asset}-${timestamp}.json`;
}

/**
 * Compact countdown like "in 2d 4h" / "in 8h" / "in 45m". Returns
 * "expired" for non-positive durations and "in <1m" for sub-minute
 * remaining time. Used in the predict-market dropdown and the review
 * pane so the user can see at a glance when the market settles.
 */
export function formatTimeUntil(targetMs: number, now: number = Date.now()): string {
  const diffMs = targetMs - now;
  if (diffMs <= 0) return 'expired';

  const totalMin = Math.floor(diffMs / 60_000);
  if (totalMin < 1)  return 'in <1m';
  if (totalMin < 60) return `in ${totalMin}m`;

  const totalH = Math.floor(totalMin / 60);
  if (totalH < 24)   return `in ${totalH}h`;

  const totalD = Math.floor(totalH / 24);
  const remH = totalH % 24;
  if (remH === 0)    return `in ${totalD}d`;
  return `in ${totalD}d ${remH}h`;
}

/**
 * Human-readable expiry label with a relative countdown.
 * Example: 1749056400000 (4 Jun 2026 17:00 UTC) viewed 2 Jun 2026
 * 13:00 UTC → "Thu 4 Jun · 17:00 UTC · in 2d 4h".
 */
export function formatExpiryLabel(ms: number, now: number = Date.now()): string {
  const d = new Date(ms);
  const dayName  = d.toLocaleDateString('en-GB', { weekday: 'short' });
  const datePart = d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  const time     = d.toLocaleTimeString('en-GB', {
    hour: '2-digit', minute: '2-digit', timeZone: 'UTC',
  });
  return `${dayName} ${datePart} · ${time} UTC · ${formatTimeUntil(ms, now)}`;
}

/**
 * Parse `insight-{ASSET}-{timestamp}.json` back into its parts. Returns
 * `null` when the filename doesn't match the convention — callers use
 * that to filter the list endpoint's output down to "real" insights
 * and ignore any other uploads the API key has produced.
 */
export function parseInsightFilename(
  filename: string,
): { asset: InsightAsset; timestamp: number } | null {
  if (!filename.startsWith(INSIGHT_FILENAME_PREFIX)) return null;
  const stem = filename.slice(INSIGHT_FILENAME_PREFIX.length);
  if (!stem.endsWith('.json')) return null;
  const middle = stem.slice(0, -'.json'.length);
  const dash = middle.lastIndexOf('-');
  if (dash < 1) return null;
  const asset = middle.slice(0, dash) as InsightAsset;
  const ts = Number(middle.slice(dash + 1));
  if (!Number.isFinite(ts) || ts <= 0) return null;
  if (!(INSIGHT_ASSETS as readonly string[]).includes(asset)) return null;
  return { asset, timestamp: ts };
}

// ─── Payload builder ────────────────────────────────────────────────────────

/**
 * Build the JSON body that gets serialized and uploaded as a file.
 * The markdown `analysis` is supplied by the caller (AI-generated at
 * publish time, not templated). Optional fields are omitted (not set to
 * null) so the on-chain blob stays minimal — every byte counts toward
 * the 100 KB cap.
 */
export function buildInsightBody(input: InsightBodyInput): InsightBody {
  const body: InsightBody = {
    title: input.title,
    asset: input.asset,
    timestamp: input.timestamp,
    analysis: input.analysis,
    includes: input.includes,
  };
  if (input.tag?.trim()) body.tag = input.tag.trim();
  if (input.source?.trim()) body.source = input.source.trim();
  return body;
}

// ─── Recent Insights table row type ─────────────────────────────────────────

/**
 * A row in the Recent Insights table. Combines the list endpoint's
 * `WalrusStorageJobStatusResponse` with the asset parsed out of the
 * filename. The body (analysis / includes) is NOT included — fetching
 * it is a separate request.
 */
export interface InsightRow {
  asset: InsightAsset;
  jobId: string;
  status: 'PENDING' | 'UPLOADING' | 'CERTIFIED' | 'FAILED';
  filename: string;
  sizeBytes: number;
  timestamp: number;
  errorMessage?: string;
  blobId?: string;
  suiObjectId?: string;
  downloadUrl?: string;
}
